CREATE DATABASE signup;
use signup;
CREATE TABLE `detail`(
  `ID` INT NOT NULL,
  `USER NAME` VARCHAR(45) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `GENDER` VARCHAR(45) NOT NULL,
  `AGE` INT NOT NULL,
  `DATE OF BIRTH` INT NOT NULL,
  `EMAIL ID` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
     PRIMARY KEY (`ID`));
SELECT * FROM `detail`;